#!/usr/bin/env python3

import rospy
import visualization_msgs.msg


rospy.init_node('marker_publisher')
pub = rospy.Publisher('/sdu/markers', visualization_msgs.msg.MarkerArray, queue_size=2)

msg = visualization_msgs.msg.MarkerArray()

marker = visualization_msgs.msg.Marker()
marker.header.frame_id = 'Needle'
marker.header.stamp = rospy.Time()
marker.ns = 'ground_truth_meshes'
marker.id = 0
marker.type = visualization_msgs.msg.Marker.MESH_RESOURCE
marker.action = visualization_msgs.msg.Marker.ADD
marker.pose.position.x, marker.pose.position.y, marker.pose.position.z = (0, 0, 0)
marker.pose.orientation.w, marker.pose.orientation.x, marker.pose.orientation.y, marker.pose.orientation.z = (1, 0, 0, 0)
marker.scale.x, marker.scale.y, marker.scale.z = (1, 1, 1)
marker.color.r, marker.color.g, marker.color.b, marker.color.a = (0, 1, 1, 1)
marker.mesh_resource = 'package://accelnet_challenge_sdu/resources/meshes/needle.obj'

msg.markers.append(marker)

while not rospy.is_shutdown():
    pub.publish(msg)
    rospy.sleep(1.0)
